### PR TITLE
Bump hedgehog dependency

### PR DESCRIPTION
**Pull request by erikd**
Would also really appreciate a Hackage metadata edit.

### CODE REVIEW

**Review by moodmosaic — APPROVED** [review]
LGTM 👍

**Comment by moodmosaic** [comment]
>[..]appreciate a Hackage metadata edit.

@erikd I don’t have maintainer rights for this package. @gwils could you do it?

**Review by endgame — CHANGES_REQUESTED** [review]
While you're in here, can you please remove the bounds on the dependencies in the example and test whether it works?

**Comment by erikd** [comment]
Yep updated and tested. All fine.

**Review by endgame — APPROVED** [review]

**Comment by endgame** [comment]
Revised on Hackage too.

**Pull request merged**
